---
roles: []

collections:
  - name: community.general
    version: "8.1.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: "1.5.4"
    source: https://galaxy.ansible.com
